version: '3.8'

services:
  joomla:
    image: joomla:5.0
    ports:
      - "8080:80"
    environment:
      PHP_UPLOAD_MAX_FILESIZE: 64M
      PHP_POST_MAX_SIZE: 64M
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: joomla_pass
      JOOMLA_DB_NAME: joomla_db
    volumes:
      - ./joomla_data:/var/www/html
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini

  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: joomla_db
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla_pass
    volumes:
      - ./db_data:/var/lib/mysql
